name: Netatmo Capture Email

on:
  schedule:
    # Changé de 59 à 42 pour éviter les pics de charge et réduire le retard de GitHub
    - cron: '42 * * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Paris
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Version stable recommandée

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run capture + email
        run: node envoi_mail.js